// this is global dummy array
// TODO : To be eliminated when data comes from the API
// import fashion from "../assets/categories/fashion.png"
// import elec from "../assets/categories/elec.png"
// import groc from "../assets/categories/groc.png"
// import footwear from "../assets/categories/footwear.png"
// import beauty from "../assets/categories/beauty.png"
// import wellness from "../assets/categories/wellness.png"

const categories = [
  {
    cat: "Home",
    expand: false,
    hasProducts: false,
  },
  {
    cat: "Fashion",
    expand: true,
    sub: ["Men", "Women", "Kids"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531187/e-commerce/fashion/nmxqtjn5kezbumgufjhq.png",
    bgColor: "#ECFFEC",
    hasProducts: true,
    items: [
      {
        name: "men's casual t-shirt",
        star: 3,
        by: "WORGN",
        disPrice: "Rs 400",
        orgPrice: "Rs 500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729541910/Fashion/uy4xyohsombs5jcvj5ww.webp",
      },
      {
        name: "men formal shirt",
        star: 5,
        by: "Highlander",
        disPrice: "Rs 1400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729541911/Fashion/yziary7y5ubb1go7dmqm.webp",
      },
      {
        name: "men casual shirt",
        star: 5,
        by: "WROGN",
        disPrice: "Rs 2400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/95b29c844c05d0f44c72e56602b25d89/detailed",
      },
      {
        name: "men casual t-shirt",
        star: 3,
        by: "Roadster",
        disPrice: "Rs 400",
        orgPrice: "Rs 800",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/d920c24744d5fb30889fe8460b8cde72/detailed",
      },
      {
        name: "men polo t-shirt",
        star: 4,
        by: "U.S.P.A",
        disPrice: "Rs 1400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/513a02b0b5955fbc84d7c8de4ff4e2e2/detailed",
      },
      {
        name: "men casual shirt",
        star: 5,
        by: "The Indian Garages",
        disPrice: "Rs 760",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/ca521f689a8c2126519ef9155839644f/detailed",
      },
      {
        name: "men matte black shirt ",
        star: 5,
        by: "WROGN",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/9c1d14ad53670e1a1eb08676c2ac123a/detailed",
      },
      {
        name: "men white polo t-shirt",
        star: 4,
        by: "U.S.P.A",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/9f26b94d5fd5649ea933e5d0e7855142/detailed",
      },
      {
        name: "women t-shirt",
        star: 3,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Women",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/ffdcad7e5fb3edfb493dac4290144980/detailed",
      },
      {
        name: "women skirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Women",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/71e4cc39bd0d5e7a956cedb8a6240f71/detailed",
      },
      {
        name: "women black dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 4300",
        orgPrice: "Rs 5600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Women",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/f266894eaff93970edc3a5216fbd6baa/detailed",
      },
      {
        name: "women floral black and white dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 4300",
        orgPrice: "Rs 6600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Women",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/9167edb716c0770849a8b550b66936aa/detailed",
      },
      {
        name: "women formal dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 2300",
        orgPrice: "Rs 3600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Women",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/cc561ec6197bc66f26e8797165faadf1/detailed",
      },
      {
        name: "kids t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/c876f4b72d9d8c3b649d6ac0406f7b6e/detailed",
      },
      {
        name: "kids t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/5ee015cc41003144058da19751423292/detailed",
      },
      {
        name: "kids multicolor t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/c2c7e2e59479b16e6766dd71a531278c/detailed",
      },
      {
        name: "kids multicolor hoodie",
        star: 4,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/e6e48d7830f13badb90caac441eed3df/detailed",
      },
      {
        name: "kids multicolor sweatshirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 2300",
        orgPrice: "Rs 2600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/7bb5790f506fb6d0296310ba603f21b7/detailed",
      },
      {
        name: "kids full sleeve t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 360",
        orgPrice: "Rs 800",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/2d0d0cda028b5c33a2b1b26abdc3a7a7/detailed",
      },
      {
        name: "kids full sleeve hoodie",
        star: 4,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 2600",
        parentCategory: "Fashion",

        availableCount: 200,
        subCategory: "Kids",
        img: "	https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/141e2169f8ce14aa205cecb35329ea16/detailed",
      },
    ],
  },
  {
    cat: "Electronics",
    expand: true,
    sub: ["Mobiles", "Headsets", "Cameras", "Laptops", "Smart Watches"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531068/e-commerce/electronics/tejx6yafsrty0vsgtw0h.png",
    bgColor: "#FEEFEA",
    hasProducts: true,
    items: [
      {
        name: "Samsung Galaxy S24 Ultra",
        star: 4,
        by: "Samsung",
        disPrice: "Rs 149000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/318deb9e77c9e14d302d3db78b6dbd88/detailed",
      },
      {
        name: "Samsung Galaxy S24+",
        star: 5,
        by: "Samsung",
        disPrice: "Rs 54000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/542b051690a5164657a1fe2dc9bca77b/detailed",
      },
      {
        name: "iPhone 16 Pro Max",
        star: 5,
        by: "Apple",
        disPrice: "Rs 164000",
        orgPrice: "Rs 179000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/934adccb4905473ca8eb4c4fc7faeffd/detailed",
      },
      {
        name: "iPhone 16",
        star: 5,
        by: "Apple",
        disPrice: "Rs 64000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/27172e5b800d483a62dd3d5be2904063/detailed",
      },
      {
        name: "Samsung Galaxy Fold 6",
        star: 5,
        by: "Samsung",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/73f1fb73ca04cd0de204383d4cc87c1d/detailed",
      },
      {
        name: "Google Pixel 9 Pro XL",
        star: 3,
        by: "Google",
        disPrice: "Rs 79000",
        orgPrice: "Rs 89000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/eb75fa5506d1ec820b87a921196ca86c/detailed",
      },
      {
        name: "Moto G85 5G",
        star: 5,
        by: "Motorola",
        disPrice: "Rs 16000",
        orgPrice: "Rs 19000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/b11007762ab26da2fb070a15cc6ac404/detailed",
      },
      {
        name: "Google Pixel 9",
        star: 3,
        by: "Google",
        disPrice: "Rs 54000",
        orgPrice: "Rs 69000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/597c316818365fdba2339d5c6c2ce6b7/detailed",
      },
      {
        name: "HyperX Cloud Alpha",
        star: 4,
        by: "HyperX",
        disPrice: "Rs 4000",
        orgPrice: "Rs 9000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/657bf04b7a800837a0bc8845bac9ff53/detailed",
      },
      {
        name: "HyperX Cloud Pro",
        star: 4,
        by: "HyperX",
        disPrice: "Rs 9000",
        orgPrice: "Rs 10000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/183efc4a5e7be891353119d5e3737b98/detailed",
      },
      {
        name: "Razer Black Shark V2 LE",
        star: 4,
        by: "Razer",
        disPrice: "Rs 14000",
        orgPrice: "Rs 19000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/3a6485f2bb17148b57c828a6111b66fb/detailed",
      },
      {
        name: "Razer Black Shark V2",
        star: 4,
        by: "Razer",
        disPrice: "Rs 4000",
        orgPrice: "Rs 9000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/70cb357a30faf62ec0103508fa14a93a/detailed",
      },
      {
        name: "MSI laptop",
        star: 4,
        by: "MSI",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/3da411a81ecb9b74b088346a7fc008f5/detailed",
      },
      {
        name: "Apple Macbook Air M2 13 inch",
        star: 5,
        by: "Apple",
        disPrice: "Rs 64000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/b31d64c293c7bf565190691b104a426b/detailed",
      },
      {
        name: "Apple Macbook Pro M3 15.6 inch, 2TB",
        star: 5,
        by: "Apple",
        disPrice: "Rs 244000",
        orgPrice: "Rs 259000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/6f5a467ca083d7fa7709f48052e18543/detailed",
      },
      {
        name: "Asus TUF A17",
        star: 4,
        by: "Asus",
        disPrice: "Rs 124000",
        orgPrice: "Rs 139000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/c6b07f894f519fe6d9cb55faaf3ffb77/detailed",
      },
      {
        name: "HP Omen Gaming",
        star: 3,
        by: "HP",
        disPrice: "Rs 44000",
        orgPrice: "Rs 59000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/22d9edb9cd5aac6641ea2e032ca1fb3c/detailed",
      },
      {
        name: "Fujifilm Camera",
        star: 4,
        by: "Fujifilm",
        disPrice: "Rs 154000",
        orgPrice: "Rs 179000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "CamerasCamera",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/2a724dfeb7b449919aef999e7dec6070/detailed",
      },
      {
        name: "Go Pro Hero 12",
        star: 5,
        by: "Go Pro",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Cameras",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/d718026baf2c5557c91ddcdf62120adb/detailed",
      },
      {
        name: "Canon 1500D EOS Camera",
        star: 5,
        by: "Canon",
        disPrice: "Rs 4000",
        orgPrice: "Rs 49000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Cameras",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/cf03018b2d3d38fc31f5bd92d6175e58/detailed",
      },
      {
        name: "Fastrack SW",
        star: 5,
        by: "Fastrack",
        disPrice: "Rs 2000",
        orgPrice: "Rs 2500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/59189a3eeb81c84f0c23b0e5fea6f855/detailed",
      },
      {
        name: "Boat SW",
        star: 5,
        by: "Boat",
        disPrice: "Rs 2200",
        orgPrice: "Rs 3500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/a158d22945cc19405a256816a635dade/detailed",
      },
      {
        name: "Apple watch series 9 SW",
        star: 5,
        by: "Apple",
        disPrice: "Rs 42000",
        orgPrice: "Rs 5500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/b32b875c8c9458246a442ab74aae9b93/detailed",
      },
      {
        name: "Apple watch ultra 2 SW",
        star: 5,
        by: "Apple",
        disPrice: "Rs 80000",
        orgPrice: "Rs 90000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/07c467536df73c1f96f89418c09abe2f/detailed",
      },
      {
        name: "Firebolt BT Calling SW",
        star: 3,
        by: "Firebolt",
        disPrice: "Rs 1200",
        orgPrice: "Rs 1500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/3d493cabef8ab8799246189d6b0da5f3/detailed",
      },
    ],
  },
  {
    cat: "Groceries",
    expand: true,
    sub: ["Ccoking Essentials", "Homecare"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531264/e-commerce/groceries/xzjo59e4ypebpxbei94g.png",
    bgColor: "#E7E7E7",
    hasProducts: true,
    items: [
      {
        name: "Surf Excel Matic",
        star: 5,
        by: "Surf Excel",
        disPrice: "Rs 150",
        orgPrice: "Rs 170",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/fd3235a6fc3e3753c4b9d96a0ffd9a79/detailed",
      },
      {
        name: "Ariel Washing Liquid",
        star: 5,
        by: "Ariel",
        disPrice: "Rs 250",
        orgPrice: "Rs 270",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/065cc02b496748771c4d6d1dde742392/detailed",
      },
      {
        name: "Surf Excel Matic 4L",
        star: 5,
        by: "Surf Excel",
        disPrice: "Rs 350",
        orgPrice: "Rs 470",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/1c5dae27fc7833a9a6500f29bd0a3dd1/detailed",
      },
      {
        name: "Ujala Supreme",
        star: 5,
        by: "Ujala",
        disPrice: "Rs 250",
        orgPrice: "Rs 270",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/42999c4e3c42eae0f92c64e59eb445e2/detailed",
      },
      {
        name: "Ezee Liquid Detergent",
        star: 4,
        by: "Ezee",
        disPrice: "Rs 250",
        orgPrice: "Rs 370",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/4d313f6f8d97b733e6e54bc8b9ef84c1/detailed",
      },
      {
        name: "6 Lentils",
        star: 5,
        by: "Nothing",
        disPrice: "Rs 230",
        orgPrice: "Rs 260",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/f83afb07fcc2137d535925e263e1fff7/detailed",
      },
      {
        name: "Office Lunch Box",
        star: 5,
        by: "Nothing",
        disPrice: "Rs 430",
        orgPrice: "Rs 660",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/e72b25a24a066a0ea55c2ec542b45531/detailed",
      },
      {
        name: "Masala Box",
        star: 3,
        by: "Nothing",
        disPrice: "Rs 230",
        orgPrice: "Rs 260",
        parentCategory: "Groceries",

        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/0a6e2f6d939d97c7e051ff147d1bc41f/detailed",
      },
    ],
  },
  {
    cat: "Footwear",
    expand: true,
    sub: ["Men", "Women", "Kids"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531230/e-commerce/footwear/dofxwiw0wy7vvaslk373.png",
    bgColor: "#DEF3FF",
    hasProducts: true,
    items: [
      {
        name: "Sparx casual walking shoe",
        star: 4,
        by: "Sparx",
        disPrice: "Rs 1969",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Men",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/4062d7fa1f54a4eea359400d95e72cc3/detailed",
      },
      {
        name: "Adidas running shoe",
        star: 4,
        by: "Adidas",
        disPrice: "Rs 3969",
        orgPrice: "Rs 5999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Men",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/9656d7c958f7a0be5337a7a68cacaed4/detailed",
      },
      {
        name: "Reebok casual walking shoe",
        star: 4,
        by: "Reebok",
        disPrice: "Rs 1969",
        orgPrice: "Rs 3999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Men",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/ea8af58b5da6e85bae7b5260722cf718/detailed",
      },
      {
        name: "Reebok running shoe",
        star: 5,
        by: "Reebok",
        disPrice: "Rs 4569",
        orgPrice: "Rs 5999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Men",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/014fd23c5b6d7e9b92a0f3087871060d/detailed",
      },
      {
        name: "Puma walking shoe",
        star: 5,
        by: "Puma",
        disPrice: "Rs 1569",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Men",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/26965a27b38f69e628ba49e8415c42f1/detailed",
      },
      {
        name: "Sparx runing shoe for women",
        star: 5,
        by: "Sparx",
        disPrice: "Rs 869",
        orgPrice: "Rs 999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Women",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/a336bd67a7a5da1093de549a3fd8d964/detailed",
      },
      {
        name: "Sandals for women",
        star: 5,
        by: "No idea",
        disPrice: "Rs 569",
        orgPrice: "Rs 699",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Women",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/c4bedb80e1df54d8ccbf7ab6e47c7d9e/detailed",
      },
      {
        name: "white Sandals for women",
        star: 5,
        by: "No idea",
        disPrice: "Rs 1869",
        orgPrice: "Rs 1999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Women",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/f29212ce87201c67e20f76a71ac6baa2/detailed",
      },
      {
        name: "Reebok running shoe for women",
        star: 5,
        by: "Reebok",
        disPrice: "Rs 2769",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Women",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/b970933f37df4d025ead6ef0705d7a29/detailed",
      },
      {
        name: "Casual sandals for women",
        star: 5,
        by: "Casuals",
        disPrice: "Rs 469",
        orgPrice: "Rs 699",
        parentCategory: "Footwear",

        availableCount: 200,
        subCategory: "Women",
        img: "https://res-console.cloudinary.com/dsqym1wwy/media_explorer_thumbnails/c55a0626e8d1bf7e776d3fae3588f0eb/detailed",
      },
    ],
  },
  {
    cat: "Beauty",
    expand: false,
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531003/e-commerce/beauty/wlbh66v6xr08oz1jrk8q.png",
    bgColor: "#FFE8F8",
    hasProducts: true,
    items: [],
  },
  {
    cat: "Wellness",
    expand: false,
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531295/e-commerce/wellness/g7navflgyefrevbyaiea.png",
    bgColor: "#C9FFD0",
    hasProducts: true,
    items: [],
  },
  {
    cat: "Shop",
    expand: true,
    hasProducts: false,
    drops: [
      {
        main: "Fashion",
        under: ["Men", "Women", "Boys", "Girls"],
      },
      {
        main: "Electronics",
        under: [
          "Mobiles",
          "TV",
          "Computers and Accessories",
          "Cameras",
          "Smart Watches and Accessories",
          "Cameras",
        ],
      },
      {
        main: "Groceries",
        under: ["Cooking Essentials", "Homecare"],
      },
      {
        main: "Footwear",
        under: ["Men's Footwear", "Women's Footwear", "Children Footwear"],
      },
      {
        main: "Beauty",
        under: [],
      },
      {
        main: "Wellness",
        under: [],
      },
    ],
  },
];

const dummy_featured_products = [
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
];

module.exports = { categories, dummy_featured_products };
