// this is global dummy array
// TODO : To be eliminated when data comes from the API
// import fashion from "../assets/categories/fashion.png"
// import elec from "../assets/categories/elec.png"
// import groc from "../assets/categories/groc.png"
// import footwear from "../assets/categories/footwear.png"
// import beauty from "../assets/categories/beauty.png"
// import wellness from "../assets/categories/wellness.png"

const categories = [
  {
    cat: "Home",
    expand: false,
    hasProducts: false,
  },
  {
    cat: "Fashion",
    expand: true,
    sub: ["Men", "Women", "Kids"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531187/e-commerce/fashion/nmxqtjn5kezbumgufjhq.png",
    bgColor: "#ECFFEC",
    hasProducts: true,
    items: [
      {
        name: "men's casual t-shirt",
        star: 3,
        by: "WORGN",
        disPrice: "Rs 400",
        orgPrice: "Rs 500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729541910/Fashion/uy4xyohsombs5jcvj5ww.webp",
      },
      {
        name: "men formal shirt",
        star: 5,
        by: "Highlander",
        disPrice: "Rs 1400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729541911/Fashion/yziary7y5ubb1go7dmqm.webp",
      },
      {
        name: "men casual shirt",
        star: 5,
        by: "WROGN",
        disPrice: "Rs 2400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456133/e-commerce/fashion/items/men/lcqi7qm8sfdrcktklzfx.webp",
      },
      {
        name: "men casual t-shirt",
        star: 3,
        by: "Roadster",
        disPrice: "Rs 400",
        orgPrice: "Rs 800",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456133/e-commerce/fashion/items/men/tufwezsxyzejghfnqsh7.webp",
      },
      {
        name: "men polo t-shirt",
        star: 4,
        by: "U.S.P.A",
        disPrice: "Rs 1400",
        orgPrice: "Rs 2500",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456133/e-commerce/fashion/items/men/bynzspc338pyp2mvjl96.webp",
      },
      {
        name: "men casual shirt",
        star: 5,
        by: "The Indian Garages",
        disPrice: "Rs 760",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456133/e-commerce/fashion/items/men/zjsctsdu6v2vcmza7tdb.webp",
      },
      {
        name: "men matte black shirt ",
        star: 5,
        by: "WROGN",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456133/e-commerce/fashion/items/men/zjsctsdu6v2vcmza7tdb.webp",
      },
      {
        name: "men white polo t-shirt",
        star: 4,
        by: "U.S.P.A",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        subCategory: "Men",
        availableCount: 200,
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456132/e-commerce/fashion/items/men/mn8jrytoomualwfydhsa.webp",
      },
      {
        name: "women t-shirt",
        star: 3,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456292/e-commerce/fashion/items/women/cclkmfpqjd9od3ktmhnd.webp",
      },
      {
        name: "women skirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456292/e-commerce/fashion/items/women/dz83lqddzek0wgofd8au.webp",
      },
      {
        name: "women black dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 4300",
        orgPrice: "Rs 5600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456292/e-commerce/fashion/items/women/xjvv2fguoyduwf5i7pdt.webp",
      },
      {
        name: "women floral black and white dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 4300",
        orgPrice: "Rs 6600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456292/e-commerce/fashion/items/women/q9loxqnjmosy4bz5vyku.webp",
      },
      {
        name: "women formal dress",
        star: 5,
        by: "no idea",
        disPrice: "Rs 2300",
        orgPrice: "Rs 3600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456292/e-commerce/fashion/items/women/virpheojpsdijorf0nmc.webp",
      },
      {
        name: "kids t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456311/e-commerce/fashion/items/kids/iqvvrg96denilyog3lcr.webp",
      },
      {
        name: "kids t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456311/e-commerce/fashion/items/kids/nxgkh1ynbabn9cmsx0tn.webp",
      },
      {
        name: "kids multicolor t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 300",
        orgPrice: "Rs 600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456311/e-commerce/fashion/items/kids/pmdwuepbvaacsolliflb.webp",
      },
      {
        name: "kids multicolor hoodie",
        star: 4,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 1600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456310/e-commerce/fashion/items/kids/prnsqwqa6gian2yadrko.webp",
      },
      {
        name: "kids multicolor sweatshirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 2300",
        orgPrice: "Rs 2600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456310/e-commerce/fashion/items/kids/w4xzueuwfz2j9jzitotl.webp",
      },
      {
        name: "kids full sleeve t-shirt",
        star: 5,
        by: "no idea",
        disPrice: "Rs 360",
        orgPrice: "Rs 800",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456310/e-commerce/fashion/items/kids/mzxuu3fmhdprtfot2cis.webp",
      },
      {
        name: "kids full sleeve hoodie",
        star: 4,
        by: "no idea",
        disPrice: "Rs 1300",
        orgPrice: "Rs 2600",
        parentCategory: "Fashion",
        availableCount: 200,
        subCategory: "Kids",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729456310/e-commerce/fashion/items/kids/jlqr2qh3v8y1ysx66mde.webp",
      },
    ],
  },
  {
    cat: "Electronics",
    expand: true,
    sub: ["Mobiles", "Headsets", "Cameras", "Laptops", "Smart Watches"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531068/e-commerce/electronics/tejx6yafsrty0vsgtw0h.png",
    bgColor: "#FEEFEA",
    hasProducts: true,
    items: [
      {
        name: "Samsung Galaxy S24 Ultra",
        star: 4,
        by: "Samsung",
        disPrice: "Rs 149000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457038/e-commerce/electronics/mobiles/lmgziok6xmpss8uhppol.webp",
      },
      {
        name: "Samsung Galaxy S24+",
        star: 5,
        by: "Samsung",
        disPrice: "Rs 54000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/gw9b7fl1p5hkk3plc7dg.webp",
      },
      {
        name: "iPhone 16 Pro Max",
        star: 5,
        by: "Apple",
        disPrice: "Rs 164000",
        orgPrice: "Rs 179000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/bnrczqj1g3ktq1phxifj.webp",
      },
      {
        name: "iPhone 16",
        star: 5,
        by: "Apple",
        disPrice: "Rs 64000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/t4tzdu16sxxtyi0vh4mt.webp",
      },
      {
        name: "Samsung Galaxy Fold 6",
        star: 5,
        by: "Samsung",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/gzfwxbeygb3u58xzrazw.webp",
      },
      {
        name: "Google Pixel 9 Pro XL",
        star: 3,
        by: "Google",
        disPrice: "Rs 79000",
        orgPrice: "Rs 89000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/thc4nukh4atdx5ehox5k.webp",
      },
      {
        name: "Moto G85 5G",
        star: 5,
        by: "Motorola",
        disPrice: "Rs 16000",
        orgPrice: "Rs 19000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457037/e-commerce/electronics/mobiles/xqpuyvkx0di7relystqh.webp",
      },
      {
        name: "Google Pixel 9",
        star: 3,
        by: "Google",
        disPrice: "Rs 54000",
        orgPrice: "Rs 69000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Mobiles",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457036/e-commerce/electronics/mobiles/bpt9yszf6mcp9lmx1iwo.webp",
      },
      {
        name: "HyperX Cloud Alpha",
        star: 4,
        by: "HyperX",
        disPrice: "Rs 4000",
        orgPrice: "Rs 9000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457197/e-commerce/electronics/headsets/aprsgohmfalnki4j1af3.jpg",
      },
      {
        name: "HyperX Cloud Pro",
        star: 4,
        by: "HyperX",
        disPrice: "Rs 9000",
        orgPrice: "Rs 10000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457197/e-commerce/electronics/headsets/nopr68a2o5xzmwoxo6iv.jpg",
      },
      {
        name: "Razer Black Shark V2 LE",
        star: 4,
        by: "Razer",
        disPrice: "Rs 14000",
        orgPrice: "Rs 19000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457197/e-commerce/electronics/headsets/vdmazhbx96wwn8o08gub.jpg",
      },
      {
        name: "Razer Black Shark V2",
        star: 4,
        by: "Razer",
        disPrice: "Rs 4000",
        orgPrice: "Rs 9000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Headsets",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457197/e-commerce/electronics/headsets/emrlzhar6wp7h7pmzszm.jpg",
      },
      {
        name: "MSI laptop",
        star: 4,
        by: "MSI",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457090/e-commerce/electronics/laptops/rnf1iypsrmbvt0n6l1mk.jpg",
      },
      {
        name: "Apple Macbook Air M2 13 inch",
        star: 5,
        by: "Apple",
        disPrice: "Rs 64000",
        orgPrice: "Rs 79000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457090/e-commerce/electronics/laptops/nbcu9agfrdfacxi5doxp.webp",
      },
      {
        name: "Apple Macbook Pro M3 15.6 inch, 2TB",
        star: 5,
        by: "Apple",
        disPrice: "Rs 244000",
        orgPrice: "Rs 259000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457090/e-commerce/electronics/laptops/ojycsi6uqacvp3mtnezt.webp",
      },
      {
        name: "Asus TUF A17",
        star: 4,
        by: "Asus",
        disPrice: "Rs 124000",
        orgPrice: "Rs 139000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457089/e-commerce/electronics/laptops/wjbcj7dng2i70hicde6r.webp",
      },
      {
        name: "HP Omen Gaming",
        star: 3,
        by: "HP",
        disPrice: "Rs 44000",
        orgPrice: "Rs 59000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Laptops",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457089/e-commerce/electronics/laptops/zdpossoga5vxdeanqqwi.jpg",
      },
      {
        name: "Fujifilm Camera",
        star: 4,
        by: "Fujifilm",
        disPrice: "Rs 154000",
        orgPrice: "Rs 179000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "CamerasCamera",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457274/e-commerce/electronics/cameras/vq8wxwdgozetxa7l1rj6.jpg",
      },
      {
        name: "Go Pro Hero 12",
        star: 5,
        by: "Go Pro",
        disPrice: "Rs 144000",
        orgPrice: "Rs 159000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Cameras",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457274/e-commerce/electronics/cameras/brecduxryofbivkrtoqq.jpg",
      },
      {
        name: "Canon 1500D EOS Camera",
        star: 5,
        by: "Canon",
        disPrice: "Rs 4000",
        orgPrice: "Rs 49000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Cameras",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457274/e-commerce/electronics/cameras/ifyhaqad6oxqabqs00j0.jpg",
      },
      {
        name: "Fastrack SW",
        star: 5,
        by: "Fastrack",
        disPrice: "Rs 2000",
        orgPrice: "Rs 2500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457352/e-commerce/electronics/smart%20watches/dl4pvfjydgzcz7h7uelm.webp",
      },
      {
        name: "Boat SW",
        star: 5,
        by: "Boat",
        disPrice: "Rs 2200",
        orgPrice: "Rs 3500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457352/e-commerce/electronics/smart%20watches/kkzx9q3xzcait9oy8bdp.webp",
      },
      {
        name: "Apple watch series 9 SW",
        star: 5,
        by: "Apple",
        disPrice: "Rs 42000",
        orgPrice: "Rs 5500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457352/e-commerce/electronics/smart%20watches/fhcgne2f53fcwoszub9x.webp",
      },
      {
        name: "Apple watch ultra 2 SW",
        star: 5,
        by: "Apple",
        disPrice: "Rs 80000",
        orgPrice: "Rs 90000",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457352/e-commerce/electronics/smart%20watches/jbl81n0jxubmhl1ve6u2.webp",
      },
      {
        name: "Firebolt BT Calling SW",
        star: 3,
        by: "Firebolt",
        disPrice: "Rs 1200",
        orgPrice: "Rs 1500",
        parentCategory: "Electronics",
        availableCount: 200,
        subCategory: "Smart Watches",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457352/e-commerce/electronics/smart%20watches/emd4nig5opdnfky3or0l.webp",
      },
    ],
  },
  {
    cat: "Groceries",
    expand: true,
    sub: ["Ccoking Essentials", "Homecare"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531264/e-commerce/groceries/xzjo59e4ypebpxbei94g.png",
    bgColor: "#E7E7E7",
    hasProducts: true,
    items: [
      {
        name: "Surf Excel Matic",
        star: 5,
        by: "Surf Excel",
        disPrice: "Rs 150",
        orgPrice: "Rs 170",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457987/e-commerce/groceries/homecare/ex7yka3yypk3navudhwp.webp",
      },
      {
        name: "Ariel Washing Liquid",
        star: 5,
        by: "Ariel",
        disPrice: "Rs 250",
        orgPrice: "Rs 270",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457986/e-commerce/groceries/homecare/felyxzwdvump3iksczqw.webp",
      },
      {
        name: "Surf Excel Matic 4L",
        star: 5,
        by: "Surf Excel",
        disPrice: "Rs 350",
        orgPrice: "Rs 470",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457986/e-commerce/groceries/homecare/o4awtoipov9rfpylpkcl.webp",
      },
      {
        name: "Ujala Supreme",
        star: 5,
        by: "Ujala",
        disPrice: "Rs 250",
        orgPrice: "Rs 270",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457986/e-commerce/groceries/homecare/pw7xr5lu3sy9byxcetcy.webp",
      },
      {
        name: "Ezee Liquid Detergent",
        star: 4,
        by: "Ezee",
        disPrice: "Rs 250",
        orgPrice: "Rs 370",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Homecare",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457985/e-commerce/groceries/homecare/f2nnjvly0omxahjhhetg.webp",
      },
      {
        name: "6 Lentils",
        star: 5,
        by: "Nothing",
        disPrice: "Rs 230",
        orgPrice: "Rs 260",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729458001/e-commerce/groceries/cooking%20essentials/nxzaj0e6kht72ylovbkx.webp",
      },
      {
        name: "Office Lunch Box",
        star: 5,
        by: "Nothing",
        disPrice: "Rs 430",
        orgPrice: "Rs 660",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729458000/e-commerce/groceries/cooking%20essentials/dakbukkrfu2gdwr1tssd.webp",
      },
      {
        name: "Masala Box",
        star: 3,
        by: "Nothing",
        disPrice: "Rs 230",
        orgPrice: "Rs 260",
        parentCategory: "Groceries",
        availableCount: 200,
        subCategory: "Cooking Essentials",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729458000/e-commerce/groceries/cooking%20essentials/ejghkgmcnmoqbt0ned5o.webp",
      },
    ],
  },
  {
    cat: "Footwear",
    expand: true,
    sub: ["Men", "Women", "Kids"],
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531230/e-commerce/footwear/dofxwiw0wy7vvaslk373.png",
    bgColor: "#DEF3FF",
    hasProducts: true,
    items: [
      {
        name: "Sparx casual walking shoe",
        star: 4,
        by: "Sparx",
        disPrice: "Rs 1969",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Men",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457742/e-commerce/footwear/mens/vtd1okgwdh4jswfzjf1l.webp",
      },
      {
        name: "Adidas running shoe",
        star: 4,
        by: "Adidas",
        disPrice: "Rs 3969",
        orgPrice: "Rs 5999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Men",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457741/e-commerce/footwear/mens/lr2bcamdzc7h5llpwyet.webp",
      },
      {
        name: "Reebok casual walking shoe",
        star: 4,
        by: "Reebok",
        disPrice: "Rs 1969",
        orgPrice: "Rs 3999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Men",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457741/e-commerce/footwear/mens/ziub0lhfhmriwlel1e20.webp",
      },
      {
        name: "Reebok running shoe",
        star: 5,
        by: "Reebok",
        disPrice: "Rs 4569",
        orgPrice: "Rs 5999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Men",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457741/e-commerce/footwear/mens/u2cgtqnmviziglywvcnd.webp",
      },
      {
        name: "Puma walking shoe",
        star: 5,
        by: "Puma",
        disPrice: "Rs 1569",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Men",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457741/e-commerce/footwear/mens/v2fdybjtoqxzonueyigc.webp",
      },
      {
        name: "Sparx running shoe for women",
        star: 5,
        by: "Sparx",
        disPrice: "Rs 869",
        orgPrice: "Rs 999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457755/e-commerce/footwear/womens/jk4zdakpfxoel8jl3jte.webp",
      },
      {
        name: "Sandals for women",
        star: 5,
        by: "No idea",
        disPrice: "Rs 569",
        orgPrice: "Rs 699",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457754/e-commerce/footwear/womens/ieirohhpkzjjuzl0d9qe.webp",
      },
      {
        name: "white Sandals for women",
        star: 5,
        by: "No idea",
        disPrice: "Rs 1869",
        orgPrice: "Rs 1999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457754/e-commerce/footwear/womens/pyz0daath84yyu4rr4uu.webp",
      },
      {
        name: "Reebok running shoe for women",
        star: 5,
        by: "Reebok",
        disPrice: "Rs 2769",
        orgPrice: "Rs 2999",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457754/e-commerce/footwear/womens/tebjuati0pcpenhdyrao.webp",
      },
      {
        name: "Casual sandals for women",
        star: 5,
        by: "Casuals",
        disPrice: "Rs 469",
        orgPrice: "Rs 699",
        parentCategory: "Footwear",
        availableCount: 200,
        subCategory: "Women",
        img: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729457753/e-commerce/footwear/womens/rgkvljn1t2dpcxklm2f2.webp",
      },
    ],
  },
  {
    cat: "Beauty",
    expand: false,
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531003/e-commerce/beauty/wlbh66v6xr08oz1jrk8q.png",
    bgColor: "#FFE8F8",
    hasProducts: true,
    items: [],
  },
  {
    cat: "Wellness",
    expand: false,
    logo: "https://res.cloudinary.com/dsqym1wwy/image/upload/v1729531295/e-commerce/wellness/g7navflgyefrevbyaiea.png",
    bgColor: "#C9FFD0",
    hasProducts: true,
    items: [],
  },
  {
    cat: "Shop",
    expand: true,
    hasProducts: false,
    drops: [
      {
        main: "Fashion",
        under: ["Men", "Women", "Boys", "Girls"],
      },
      {
        main: "Electronics",
        under: [
          "Mobiles",
          "TV",
          "Computers and Accessories",
          "Cameras",
          "Smart Watches and Accessories",
          "Cameras",
        ],
      },
      {
        main: "Groceries",
        under: ["Cooking Essentials", "Homecare"],
      },
      {
        main: "Footwear",
        under: ["Men's Footwear", "Women's Footwear", "Children Footwear"],
      },
      {
        main: "Beauty",
        under: [],
      },
      {
        main: "Wellness",
        under: [],
      },
    ],
  },
];

const dummy_featured_products = [
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "iPhone 15",
    star: 5,
    by: "Applee",
    disPrice: "Rs 54000",
    orgPrice: "Rs 79000",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729062467/1729062465538_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp",
  },
  {
    name: "men t-shirt",
    star: 4,
    by: "some_name",
    disPrice: "Rs 400",
    orgPrice: "Rs 500",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729063519/1729063513478_1000014029787-Green-GREEN-1000014029787_01-2100.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
  {
    name: "Nike air janardan 69",
    star: 5,
    by: "Nike",
    disPrice: "Rs 6969",
    orgPrice: "Rs 8999",
    img: "https://res.cloudinary.com/dy2p0n2xc/image/upload/v1729061510/1729061501881_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.jpg",
  },
];

module.exports = { categories, dummy_featured_products };
